export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS"
export const GET_SEARCH_PAGE = "GET_SEARCH_PAGE"
export const RESET_SEARCH_PAGE = "RESET_SEARCH_PAGE"
export const GET_SINGLE_LIST = "GET_SINGLE_LIST"